### ISSUE TITLE
SDE if in-scope delimiter value clashes with an escapeCharacter or escapeEscapeCharacter value 

### ISSUE THREAD

**Issue by mbeckerle** [OpenGridForum/DFDL#25]
(was Action 323)
Spec is not clear this is an error. 

Verified that IBM DFDL throws SDE.

**Comment by smhdfdl** [comment]
This issue applies to escapeCharacter & escapeEscapeCharacter when escapeKind is 'escapeCharacter'. It does *not* apply to escapeEscapeCharacter when escapeKind is 'escapeBlock' (because we are not scanning for delimiters within an escape block) nor to escapeBlockEnd (because we are not scanning for delimiters within an escape block) nor to escapeBlockStart (because we do not scan for that). .

**Comment by smhdfdl** [comment]
Reviewed on WG call 2023-05-11. Agreed the above changes are all that is needed.
