### ISSUE TITLE
Number of Digits in Calendar Pattern should be enforced (ICU)

### ISSUE THREAD

**Issue by mbeckerle** [OpenGridForum/DFDL#42]
From Action 330.

Decided to document this as erratum on DFDL v1.0.

**Comment by smhdfdl** [comment]
Following updates needed.

Table 40 in section 13.11.1. This is largely correct, because it already has (eg) dd => 02. There are some updates though, to correct existing bugs
a)  M - should be '9' not '09'
b)  ee - should be '02' not '2'

ICU have effectively stopped an example of lenient parsing when in 'strict' mode. We didn't document this particular example so there is nothing more to change.

**Comment by smhdfdl** [comment]
Reviewed on WG call 2023-05-11. Agreed the above changes are all that is needed.

**Comment by mbeckerle** [comment]
Fixed by https://github.com/OpenGridForum/DFDL/pull/45
